# Generated by Django 6.0.3 on 2026-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_middle_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('student_father_name', models.CharField(max_length=30)),
                ('student_mother_name', models.CharField(max_length=30)),
                ('student_mobile_no', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_aadhar_no', models.CharField(max_length=30)),
                ('student_dob', models.DateField()),
                ('student_gender', models.CharField(max_length=15)),
                ('student_course', models.CharField(max_length=50)),
                ('student_branch', models.CharField(max_length=50)),
                ('student_year', models.CharField(max_length=10)),
                ('student_category', models.CharField(max_length=30)),
                ('student_permanent_addresss', models.TextField()),
            ],
        ),
    ]
