# Generated by Django 6.0.4 on 2026-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='form_pdf',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
    ]
