# Generated by Django 6.0.4 on 2026-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_form_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='form_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='forms/'),
        ),
    ]
